const NS_WEATHER_FORECAST = 'WeatherForecast';

const CURRENT_LOCATION_WEATHER_DATA = 'CURRENT_LOCATION_WEATHER_DATA';

const GET_QUERY_LOCATION = 'GET_QUERY_LOCATION';
const SET_QUERY_LOCATION = 'SET_QUERY_LOCATION';

const GET_WEATHER_DATA = 'GET_WEATHER_DATA';
const SET_WEATHER_DATA = 'SET_WEATHER_DATA';

const CLEAR_REDUX_DATA = 'CLEAR_REDUX_DATA';

export default {
  NS_WEATHER_FORECAST,

  CURRENT_LOCATION_WEATHER_DATA,

  GET_QUERY_LOCATION,
  SET_QUERY_LOCATION,

  GET_WEATHER_DATA,
  SET_WEATHER_DATA,

  CLEAR_REDUX_DATA,
};
